post/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.PostView.as_view()),
    path("home/", views.home),
    path("category/<str:url>", views.move_category, name='move_category'),
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<str:slug>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<str:slug>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path("review/<int:pk>/", views.AddReview.as_view(), name='add_review'),
    path("about/<str:slug>", views.MagazineView.as_view(), name='magazine_detail'),
    path('market/<str:username>', views.MagazinePostListView.as_view(), name='magazine_posts'),
    path("add-rating", views.AddStarRating.as_view(), name='add_rating'),
    path("product/<slug:slug>/", views.PostDetailView.as_view(), name='post_detail'),

]

telepost/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    path('', include("post.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from transliterate import translit
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.conf import settings
from django.contrib.auth import get_user_model

from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    url = models.SlugField(max_length=70, unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        super(Category, self).save()
        if self.parent.mptt_level is not None:
            if self.parent.mptt_level == 3:
                raise ValueError(u'Достигнута максимальная вложенность!')
        if not self.url:
            self.url = slugify(translit(self.name, 'ru', reversed=True))
            super(Category, self).save()
        elif self.url != slugify(translit(self.name, 'ru', reversed=True)):
            self.url = slugify(translit(self.name, 'ru', reversed=True))
            super(Category, self).save()
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class MPTTMeta:
        level_attr = 'mptt_level'
        order_insertion_by = ['name']

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Magazine(models.Model):
    """Магазин"""
    market = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="название")
    telelink = models.CharField("Ссылка на телеграм", max_length=100)
    delivery = models.BooleanField(default=False, verbose_name="Доставка")
    click_uz = models.BooleanField(default=False, verbose_name="Онлайн платёж")
    poster = models.ImageField("Главное фото", upload_to="product_images/", default="default.jpeg", blank=True,
                               null=True)

    def __str__(self):
        return self.market.username

    class Meta:
        verbose_name = "Магазин"
        verbose_name_plural = "Магазины"

    def get_absolute_url(self):
        return reverse('magazine_detail', kwargs={"slug": self.market})

    def get_magazine_posts(self):
        return reverse("magazine_posts", kwargs={"username": self.market})


class Post(models.Model):
    """Пост"""
    title = models.CharField("Название", max_length=64)
    poster = models.ImageField("Главное фото", upload_to="product_images/", default="default.jpeg", blank=True,
                               null=True)
    description = models.TextField("Описание")
    characteristics = models.TextField("Характеристики", blank=True, null=True, default="Нет характеристики.")
    price = models.PositiveIntegerField("Стоимость", default=0, help_text="Указывать в сумах")
    old = models.PositiveIntegerField("Старая цена", blank=True, null=True)
    magazine = models.ForeignKey(Magazine, verbose_name="Поставщик",
                                 on_delete=models.SET_DEFAULT, default='Magazine')
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=70, unique=True)
    draft = models.BooleanField("Черновик", default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"slug": self.url})

    def get_magazine_posts(self):
        return reverse("magazine_posts", kwargs={"slug": self.magazine.market.username})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    def save(self, **kwargs):
        super(Post, self).save()
        if not self.url:
            self.url = slugify(translit(self.title, 'ru', reversed=True)) + '-' + str(self.id)
            super(Post, self).save()
        elif self.url != slugify(translit(self.title, 'ru', reversed=True)):
            self.url = slugify(translit(self.title, 'ru', reversed=True))
            super(Post, self).save()


class PostImages(models.Model):
    """Изображения поста в большом количестве"""
    post = models.ForeignKey(Post, verbose_name="Пост", blank=True, null=True, on_delete=models.CASCADE, default=None)
    titleimage = models.CharField("Заголовок", max_length=100, blank=True, null=True, default="image_title")
    # description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="product_images/", blank=True, null=True, default="Изображение "
                                                                                                         "продукта")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.title = None

    def __str__(self):
        return self.titleimage

    class Meta:
        verbose_name = "Фотки поста"
        verbose_name_plural = "Фотки поста"


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Звезда рейтинга"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="пост")

    def __str__(self):
        return f"{self.star} - {self.post}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey('self', verbose_name="Родитель",
                               on_delete=models.SET_NULL, blank=True, null=True)
    post = models.ForeignKey(Post, verbose_name="пост", on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} - {self.post}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

templates/market/market_detail.html
{% extends 'post/base.html' %}{% load post_tag %}
{% block content %}




<!-- BREADCRUMB -->
		<div id="breadcrumb" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<h3 class="breadcrumb-header">{{ mpost.market.username }}</h3>
						<ul class="breadcrumb-tree">
							<li><a href="/">Главная</a></li>
							<li class="active">Страница магазина</li>
						</ul>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /BREADCRUMB -->

Название: {{ mpost.market.username }}<br>
Ссылка: {{ mpost.telelink }}<br>
<a href="{{ mpost.get_magazine_posts }}">Все товары магазина</a><br><br><br><br>


    <!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">

					<!-- section title -->
					<div class="col-md-12">
						<div class="section-title">
							<h3 class="title">Популярные товары магазина</h3>
{#							<div class="section-nav">#}
{#								<ul class="section-tab-nav tab-nav">#}
{#									<li class="active"><a data-toggle="tab" href="#tab1">Ноутбуки</a></li>#}
{#									<li><a data-toggle="tab" href="#tab1">Смартфоны</a></li>#}
{#									<li><a data-toggle="tab" href="#tab1">Камеры</a></li>#}
{#									<li><a data-toggle="tab" href="#tab1">Аксессуары</a></li>#}
{#								</ul>#}
{#							</div>#}
						</div>
					</div>
					<!-- /section title -->

					<!-- Products tab & slick -->
					<div class="col-md-12">
						<div class="row">
							<div class="products-tabs">
								<!-- tab -->
								<div id="tab1" class="tab-pane active">
									<div class="products-slick" data-nav="#slick-nav-1">
										{% for post in mpost.post_set.all %}
                                        <!-- product -->
										<div class="product">
											<div class="product-img">
												<img src="{{ post.poster.url }}" alt="">
												<div class="product-label">
													<span class="sale">-30%</span>
													<span class="new">Новинка</span>
												</div>
											</div>
											<div class="product-body">
												<p class="product-category">Категория</p>
												<h3 class="product-name"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
												<h4 class="product-price">${{ post.price }} {% if post.old %}<del class="product-old-price">${{ post.old }}</del>{% endif %}</h4>
												<div class="product-rating">
													<i class="fa fa-star"></i>
													<i class="fa fa-star"></i>
													<i class="fa fa-star"></i>
													<i class="fa fa-star"></i>
													<i class="fa fa-star"></i>
												</div>
												<div class="product-btns">
													<button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">Добавить в Избранное</span></button>
													<button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">Добавить в сравнение</span></button>
													<button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">быстрый просмотр</span></button>
												</div>
											</div>
											<div class="add-to-cart">
												<button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> Добавить в Корзину</button>
											</div>
										</div>
										<!-- /product -->
                                        {% endfor %}
									</div>
									<div id="slick-nav-1" class="products-slick-nav"></div>
								</div>
								<!-- /tab -->
							</div>
						</div>
                        <br><br><br>
                        <div class="hot-deal">
                            <a class="primary-btn cta-btn" href="{{ mpost.get_magazine_posts }}">Все товары магазина</a>
                        </div>
					</div>

					<!-- Products tab & slick -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->


{% endblock %}